# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/영업mbo/dialog/ui/dlg_년간목표치생성.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(266, 197)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_btn = QtWidgets.QFrame(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btn.sizePolicy().hasHeightForWidth())
        self.frame_btn.setSizePolicy(sizePolicy)
        self.frame_btn.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_btn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_btn.setObjectName("frame_btn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btn)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.PB_Save = QtWidgets.QPushButton(parent=self.frame_btn)
        self.PB_Save.setEnabled(False)
        self.PB_Save.setToolTip("")
        self.PB_Save.setObjectName("PB_Save")
        self.horizontalLayout_2.addWidget(self.PB_Save)
        self.verticalLayout_2.addWidget(self.frame_btn)
        self.frame_Form = QtWidgets.QFrame(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_Form.sizePolicy().hasHeightForWidth())
        self.frame_Form.setSizePolicy(sizePolicy)
        self.frame_Form.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_Form.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Form.setObjectName("frame_Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=self.frame_Form)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox)
        self.checkBox_Jojik = QtWidgets.QCheckBox(parent=self.frame_Form)
        self.checkBox_Jojik.setTristate(True)
        self.checkBox_Jojik.setObjectName("checkBox_Jojik")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_Jojik)
        self.checkBox_Jojik_new = QtWidgets.QCheckBox(parent=self.frame_Form)
        self.checkBox_Jojik_new.setObjectName("checkBox_Jojik_new")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_Jojik_new)
        self.checkBox_Gaein = QtWidgets.QCheckBox(parent=self.frame_Form)
        self.checkBox_Gaein.setTristate(True)
        self.checkBox_Gaein.setObjectName("checkBox_Gaein")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_Gaein)
        self.checkBox_Gaein_new = QtWidgets.QCheckBox(parent=self.frame_Form)
        self.checkBox_Gaein_new.setObjectName("checkBox_Gaein_new")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_Gaein_new)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.frame_Form)

        self.retranslateUi(Dialog)
        # QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "년간목표 생성"))
        Dialog.setToolTip(_translate("Dialog", "록"))
        self.PB_Save.setText(_translate("Dialog", "저장"))
        self.label.setText(_translate("Dialog", "대상년도"))
        self.checkBox_Jojik.setText(_translate("Dialog", "조직"))
        self.checkBox_Jojik_new.setText(_translate("Dialog", "신규"))
        self.checkBox_Gaein.setText(_translate("Dialog", "개인"))
        self.checkBox_Gaein_new.setText(_translate("Dialog", "신규"))
