# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/dialog/loading/ui/dlg_loading.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Dialog_loading(object):
    def setupUi(self, Dialog_loading):
        Dialog_loading.setObjectName("Dialog_loading")
        Dialog_loading.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_loading.sizePolicy().hasHeightForWidth())
        Dialog_loading.setSizePolicy(sizePolicy)
        Dialog_loading.setMinimumSize(QtCore.QSize(300, 300))
        Dialog_loading.setMaximumSize(QtCore.QSize(300, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_loading)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_loading = QtWidgets.QLabel(parent=Dialog_loading)
        self.label_loading.setScaledContents(True)
        self.label_loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout.addWidget(self.label_loading)

        self.retranslateUi(Dialog_loading)
        # QtCore.QMetaObject.connectSlotsByName(Dialog_loading)

    def retranslateUi(self, Dialog_loading):
        _translate = QtCore.QCoreApplication.translate
        Dialog_loading.setWindowTitle(_translate("Dialog_loading", "Dialog"))
        self.label_loading.setText(_translate("Dialog_loading", "TextLabel"))
