# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/compoent_v2/pagenation/pagination.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_wid_pagination(object):
    def setupUi(self, wid_pagination):
        wid_pagination.setObjectName("wid_pagination")
        wid_pagination.setEnabled(True)
        wid_pagination.resize(1367, 32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wid_pagination.sizePolicy().hasHeightForWidth())
        wid_pagination.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(wid_pagination)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_Pagenation = QtWidgets.QFrame(parent=wid_pagination)
        self.frame_Pagenation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Pagenation.sizePolicy().hasHeightForWidth())
        self.frame_Pagenation.setSizePolicy(sizePolicy)
        self.frame_Pagenation.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_Pagenation.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Pagenation.setObjectName("frame_Pagenation")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_Pagenation)
        self.horizontalLayout_3.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_Pagenation)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_countTotal = QtWidgets.QLabel(parent=self.frame_Pagenation)
        self.label_countTotal.setObjectName("label_countTotal")
        self.horizontalLayout_3.addWidget(self.label_countTotal)
        spacerItem = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_Pagenation)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.comboBox_current_Page = QtWidgets.QComboBox(parent=self.frame_Pagenation)
        self.comboBox_current_Page.setObjectName("comboBox_current_Page")
        self.horizontalLayout_3.addWidget(self.comboBox_current_Page)
        self.label_total_Page = QtWidgets.QLabel(parent=self.frame_Pagenation)
        self.label_total_Page.setObjectName("label_total_Page")
        self.horizontalLayout_3.addWidget(self.label_total_Page)
        spacerItem1 = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_Pagenation)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.comboBox_countOnPage = Combo_table_row(parent=self.frame_Pagenation)
        self.comboBox_countOnPage.setObjectName("comboBox_countOnPage")
        self.horizontalLayout_3.addWidget(self.comboBox_countOnPage)
        spacerItem2 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.PB_DownloadAll = QtWidgets.QPushButton(parent=self.frame_Pagenation)
        self.PB_DownloadAll.setObjectName("PB_DownloadAll")
        self.horizontalLayout_3.addWidget(self.PB_DownloadAll)
        self.verticalLayout.addWidget(self.frame_Pagenation)

        self.retranslateUi(wid_pagination)
        # QtCore.QMetaObject.connectSlotsByName(wid_pagination)

    def retranslateUi(self, wid_pagination):
        _translate = QtCore.QCoreApplication.translate
        wid_pagination.setWindowTitle(_translate("wid_pagination", "Form"))
        self.label_9.setText(_translate("wid_pagination", "검색결과"))
        self.label_countTotal.setText(_translate("wid_pagination", "0건"))
        self.label_11.setText(_translate("wid_pagination", "현재 Page"))
        self.label_total_Page.setText(_translate("wid_pagination", "/ 전체  Page"))
        self.label_12.setText(_translate("wid_pagination", "Table Row수"))
        self.PB_DownloadAll.setText(_translate("wid_pagination", "검색결과 다운로드"))
from modules.PyQt.component.combo_custom import Combo_table_row
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


