# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/webEngineViewTest.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(914, 679)
        self.webEngineView_Test = QtWebEngineWidgets.QWebEngineView(parent=Dialog)
        self.webEngineView_Test.setGeometry(QtCore.QRect(10, 10, 891, 571))
        self.webEngineView_Test.setUrl(QtCore.QUrl("https://wikidocs.net/book/2944"))
        self.webEngineView_Test.setObjectName("webEngineView_Test")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 590, 891, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_url = QtWidgets.QLineEdit(parent=self.widget)
        self.line_url.setObjectName("line_url")
        self.horizontalLayout.addWidget(self.line_url)
        self.btn_setUrl = QtWidgets.QPushButton(parent=self.widget)
        self.btn_setUrl.setObjectName("btn_setUrl")
        self.horizontalLayout.addWidget(self.btn_setUrl)
        self.widget1 = QtWidgets.QWidget(parent=Dialog)
        self.widget1.setGeometry(QtCore.QRect(440, 630, 458, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_back = QtWidgets.QPushButton(parent=self.widget1)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        self.btn_forward = QtWidgets.QPushButton(parent=self.widget1)
        self.btn_forward.setObjectName("btn_forward")
        self.horizontalLayout_2.addWidget(self.btn_forward)
        self.btn_reload = QtWidgets.QPushButton(parent=self.widget1)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout_2.addWidget(self.btn_reload)
        self.btn_stop = QtWidgets.QPushButton(parent=self.widget1)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_setUrl.setText(_translate("Dialog", "Go"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.btn_forward.setText(_translate("Dialog", "Forward"))
        self.btn_reload.setText(_translate("Dialog", "Reload"))
        self.btn_stop.setText(_translate("Dialog", "Stop"))
from PyQt6 import QtWebEngineWidgets
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


