# Generated by Django 5.1 on 2025-03-17 04:47

from django.db import migrations, models
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='table_name', max_length=250)),
                ('table_style', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('column_name', models.CharField(default='columns_name', max_length=250)),
                ('display_name', models.CharField(default='display_name', max_length=250)),
                ('column_type', models.CharField(default='CharField', max_length=250)),
                ('column_width', models.IntegerField(default=0)),
                ('cell_style', models.JSONField(default={})),
                ('is_editable', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('header_menu', models.CharField(blank=True, max_length=250, null=True)),
                ('cell_menu', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
