# Generated by Django 5.1 on 2025-03-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('user_mailid', models.CharField(default='', max_length=250)),
                ('user_성명', models.CharField(default='', max_length=250)),
                ('refresh_token', models.CharField(default='', help_text='server 에서 경우에 따라서 발급함', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
