# Generated by Django 5.1 on 2025-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0002_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='is_auto_login',
            field=models.BooleanField(default=False),
        ),
    ]
