# Generated by Django 5.1 on 2025-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0003_login_user_is_auto_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.IntegerField(default=16)),
                ('font_bold', models.BooleanField(default=True)),
                ('toolbar_color', models.CharField(default='#f6f5f4', max_length=20)),
                ('toolbar_bg_color', models.CharField(default='#000000', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'toolbar_settings',
            },
        ),
    ]
