# Generated by Django 5.1 on 2025-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0004_toolbarsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbarsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
