# Generated by Django 5.1 on 2025-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0005_toolbarsettings_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appID', models.IntegerField(default=-1)),
                ('search_text', models.CharField(default='', max_length=250)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
    ]
