# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/serial/ui/serial_관리.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Tab_App(object):
    def setupUi(self, Tab_App):
        Tab_App.setObjectName("Tab_App")
        Tab_App.resize(1388, 1175)
        self.verticalLayout = QtWidgets.QVBoxLayout(Tab_App)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_info = QtWidgets.QFrame(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy)
        self.frame_info.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_info = QtWidgets.QPushButton(parent=self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_info.sizePolicy().hasHeightForWidth())
        self.pb_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.pb_info.setFont(font)
        self.pb_info.setObjectName("pb_info")
        self.horizontalLayout.addWidget(self.pb_info)
        self.label_target = QtWidgets.QLabel(parent=self.frame_info)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_target.setFont(font)
        self.label_target.setStyleSheet("background-color:black;color:yellow;")
        self.label_target.setObjectName("label_target")
        self.horizontalLayout.addWidget(self.label_target)
        spacerItem = QtWidgets.QSpacerItem(1238, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_info)
        self.frame_search = QtWidgets.QFrame(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_search.sizePolicy().hasHeightForWidth())
        self.frame_search.setSizePolicy(sizePolicy)
        self.frame_search.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_search.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_search.setObjectName("frame_search")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_search)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_search)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_Serial = QtWidgets.QLineEdit(parent=self.frame_search)
        self.lineEdit_Serial.setObjectName("lineEdit_Serial")
        self.horizontalLayout_2.addWidget(self.lineEdit_Serial)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBox_Jakji = QtWidgets.QCheckBox(parent=self.frame_search)
        self.checkBox_Jakji.setObjectName("checkBox_Jakji")
        self.horizontalLayout_2.addWidget(self.checkBox_Jakji)
        self.checkBox_Sangji = QtWidgets.QCheckBox(parent=self.frame_search)
        self.checkBox_Sangji.setObjectName("checkBox_Sangji")
        self.horizontalLayout_2.addWidget(self.checkBox_Sangji)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pb_scan = QtWidgets.QPushButton(parent=self.frame_search)
        self.pb_scan.setObjectName("pb_scan")
        self.horizontalLayout_2.addWidget(self.pb_scan)
        self.pb_search = QtWidgets.QPushButton(parent=self.frame_search)
        self.pb_search.setEnabled(False)
        self.pb_search.setObjectName("pb_search")
        self.horizontalLayout_2.addWidget(self.pb_search)
        self.verticalLayout.addWidget(self.frame_search)
        self.frame_main = QtWidgets.QFrame(parent=Tab_App)
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout.addWidget(self.frame_main)

        self.retranslateUi(Tab_App)
        # QtCore.QMetaObject.connectSlotsByName(Tab_App)

    def retranslateUi(self, Tab_App):
        _translate = QtCore.QCoreApplication.translate
        Tab_App.setWindowTitle(_translate("Tab_App", "Form"))
        self.pb_info.setText(_translate("Tab_App", "?"))
        self.label_target.setText(_translate("Tab_App", "TextLabel"))
        self.label.setText(_translate("Tab_App", "Serial"))
        self.checkBox_Jakji.setText(_translate("Tab_App", "작업지시서"))
        self.checkBox_Sangji.setText(_translate("Tab_App", "생산지시서"))
        self.pb_scan.setText(_translate("Tab_App", "Scan"))
        self.pb_search.setText(_translate("Tab_App", "조회"))
