# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/HR평가/ui/tab_HR평가_상급자평가.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab_App(object):
    def setupUi(self, Tab_App):
        Tab_App.setObjectName("Tab_App")
        Tab_App.resize(1345, 853)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tab_App.sizePolicy().hasHeightForWidth())
        Tab_App.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Tab_App)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_info = QtWidgets.QFrame(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy)
        self.frame_info.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_info = QtWidgets.QPushButton(parent=self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_info.sizePolicy().hasHeightForWidth())
        self.pb_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.pb_info.setFont(font)
        self.pb_info.setObjectName("pb_info")
        self.horizontalLayout.addWidget(self.pb_info)
        spacerItem = QtWidgets.QSpacerItem(1238, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_Submit = QtWidgets.QPushButton(parent=self.frame_info)
        self.PB_Submit.setObjectName("PB_Submit")
        self.horizontalLayout.addWidget(self.PB_Submit)
        self.verticalLayout.addWidget(self.frame_info)
        self.frame = QtWidgets.QFrame(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(32)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_1 = QtWidgets.QPushButton(parent=self.frame)
        self.PB_1.setObjectName("PB_1")
        self.horizontalLayout_2.addWidget(self.PB_1)
        self.PB_2 = QtWidgets.QPushButton(parent=self.frame)
        self.PB_2.setObjectName("PB_2")
        self.horizontalLayout_2.addWidget(self.PB_2)
        self.PB_3 = QtWidgets.QPushButton(parent=self.frame)
        self.PB_3.setObjectName("PB_3")
        self.horizontalLayout_2.addWidget(self.PB_3)
        self.PB_4 = QtWidgets.QPushButton(parent=self.frame)
        self.PB_4.setObjectName("PB_4")
        self.horizontalLayout_2.addWidget(self.PB_4)
        self.PB_5 = QtWidgets.QPushButton(parent=self.frame)
        self.PB_5.setObjectName("PB_5")
        self.horizontalLayout_2.addWidget(self.PB_5)
        spacerItem1 = QtWidgets.QSpacerItem(968, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_Pyungga = QtWidgets.QFrame(parent=Tab_App)
        self.frame_Pyungga.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Pyungga.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Pyungga.setObjectName("frame_Pyungga")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_Pyungga)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wid_Table_Pyungga_gaebul = Wid_Table_for_HR평가_상급자평가_개별(parent=self.frame_Pyungga)
        self.wid_Table_Pyungga_gaebul.setObjectName("wid_Table_Pyungga_gaebul")
        self.verticalLayout_2.addWidget(self.wid_Table_Pyungga_gaebul)
        self.wid_Table_Pyungga_Jonghab = Wid_Table_for_HR평가_상급자평가_종합(parent=self.frame_Pyungga)
        self.wid_Table_Pyungga_Jonghab.setObjectName("wid_Table_Pyungga_Jonghab")
        self.verticalLayout_2.addWidget(self.wid_Table_Pyungga_Jonghab)
        self.verticalLayout.addWidget(self.frame_Pyungga)

        self.retranslateUi(Tab_App)
        # QtCore.QMetaObject.connectSlotsByName(Tab_App)

    def retranslateUi(self, Tab_App):
        _translate = QtCore.QCoreApplication.translate
        Tab_App.setWindowTitle(_translate("Tab_App", "Form"))
        self.pb_info.setText(_translate("Tab_App", "?"))
        self.PB_Submit.setText(_translate("Tab_App", "제출"))
        self.PB_1.setText(_translate("Tab_App", "1차평가"))
        self.PB_2.setText(_translate("Tab_App", "2차평가"))
        self.PB_3.setText(_translate("Tab_App", "3차평가"))
        self.PB_4.setText(_translate("Tab_App", "4차평가"))
        self.PB_5.setText(_translate("Tab_App", "5차평가"))
from modules.PyQt.Tabs.HR평가.tables.table_HR평가_상급자평가_개별 import Wid_Table_for_HR평가_상급자평가_개별
from modules.PyQt.Tabs.HR평가.tables.table_HR평가_상급자평가_종합 import Wid_Table_for_HR평가_상급자평가_종합
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


