# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkt/development/python/gui/Shinwoo_APP_ver0.09/modules/PyQt6/component/ui/combo_lineedit.ui'
#
# Created by: PyQt6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(139, 66)
        self.vLayout = QtWidgets.QVBoxLayout(Form)
        self.vLayout.setContentsMargins(-1, 0, -1, 0)
        self.vLayout.setSpacing(0)
        self.vLayout.setObjectName("vLayout")
        self.combo = QtWidgets.QComboBox(Form)
        self.combo.setObjectName("combo")
        self.vLayout.addWidget(self.combo)
        self.line = QtWidgets.QLineEdit(Form)
        self.line.setObjectName("line")
        self.vLayout.addWidget(self.line)

        self.retranslateUi(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
