# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkt/development/python/gui/Shinwoo_APP_ver0.09/modules/PyQt6/component/ui/imageViewer.ui'
#
# Created by: PyQt6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.vLayout = QtWidgets.QVBoxLayout(Form)
        self.vLayout.setContentsMargins(0, 0, 0, 0)
        self.vLayout.setObjectName("vLayout")
        self.label_ImageView = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_ImageView.setFont(font)
        self.label_ImageView.setAcceptDrops(True)
        self.label_ImageView.setStyleSheet("border: 4px dashed #aaa;")
        self.label_ImageView.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ImageView.setObjectName("label_ImageView")
        self.vLayout.addWidget(self.label_ImageView)

        self.retranslateUi(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ImageViewer"))
        self.label_ImageView.setText(_translate("Form", "Image file을 넣으세요"))
