# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkt/development/python/gui/Shinwoo_APP_ver0.09/modules/PyQt6/component/ui/생산지시서_종류.ui'
#
# Created by: PyQt6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radio_HY = QtWidgets.QRadioButton(Form)
        self.radio_HY.setObjectName("radio_HY")
        self.horizontalLayout.addWidget(self.radio_HY)
        self.radio_OTIS = QtWidgets.QRadioButton(Form)
        self.radio_OTIS.setObjectName("radio_OTIS")
        self.horizontalLayout.addWidget(self.radio_OTIS)
        self.radio_TKE = QtWidgets.QRadioButton(Form)
        self.radio_TKE.setObjectName("radio_TKE")
        self.horizontalLayout.addWidget(self.radio_TKE)
        self.radio_ETC = QtWidgets.QRadioButton(Form)
        self.radio_ETC.setObjectName("radio_ETC")
        self.horizontalLayout.addWidget(self.radio_ETC)

        self.retranslateUi(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "생산지시서 종류:         "))
        self.radio_HY.setText(_translate("Form", "현대"))
        self.radio_OTIS.setText(_translate("Form", "OTIS"))
        self.radio_TKE.setText(_translate("Form", "TKE"))
        self.radio_ETC.setText(_translate("Form", "기타"))
