# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/webEngine/googlemap/ui/google_map_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(732, 668)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formFrame = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEditJuso = QtWidgets.QLineEdit(parent=self.formFrame)
        self.lineEditJuso.setObjectName("lineEditJuso")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditJuso)
        self.horizontalLayout.addWidget(self.formFrame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_Search = QtWidgets.QPushButton(parent=self.frame)
        self.PB_Search.setObjectName("PB_Search")
        self.horizontalLayout.addWidget(self.PB_Search)
        self.verticalLayout.addWidget(self.frame)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.frame_googleMap = QtWidgets.QFrame(parent=Dialog)
        self.frame_googleMap.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_googleMap.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_googleMap.setObjectName("frame_googleMap")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_googleMap)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wid_GoogleMap = QGoogleMap(parent=self.frame_googleMap)
        self.wid_GoogleMap.setObjectName("wid_GoogleMap")
        self.verticalLayout_2.addWidget(self.wid_GoogleMap)
        self.verticalLayout.addWidget(self.frame_googleMap)

        self.retranslateUi(Dialog)
        # QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Google Map"))
        self.label.setText(_translate("Dialog", "주소"))
        self.PB_Search.setText(_translate("Dialog", "검색"))
        self.label_2.setText(_translate("Dialog", "지도위치가 로딩이 안되면 다시 검색을 눌러 주십시요( 네트워크 연결 상태 등에 따라 로딩 시간이 다릅니다.)"))
from modules.webEngine.googlemap.google_map_my import QGoogleMap
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


