# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/sub_window/win_app사용자/ui/tab_app사용자.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab(object):
    def setupUi(self, Tab):
        Tab.setObjectName("Tab")
        Tab.resize(1345, 853)
        self.vLayout_main = QtWidgets.QVBoxLayout(Tab)
        self.vLayout_main.setObjectName("vLayout_main")
        self.Wid_Search_for = Wid_Search_for(parent=Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wid_Search_for.sizePolicy().hasHeightForWidth())
        self.Wid_Search_for.setSizePolicy(sizePolicy)
        self.Wid_Search_for.setObjectName("Wid_Search_for")
        self.vLayout_main.addWidget(self.Wid_Search_for)
        self.Wid_Table = Wid_Table_for_app사용자(parent=Tab)
        self.Wid_Table.setObjectName("Wid_Table")
        self.vLayout_main.addWidget(self.Wid_Table)

        self.retranslateUi(Tab)
        # QtCore.QMetaObject.connectSlotsByName(Tab)

    def retranslateUi(self, Tab):
        _translate = QtCore.QCoreApplication.translate
        Tab.setWindowTitle(_translate("Tab", "Form"))
from modules.PyQt.sub_window.win_app사용자.component.Wid_search_for import Wid_Search_for
from modules.PyQt.sub_window.win_app사용자.table.table_app사용자 import Wid_Table_for_app사용자
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


