import sys
from PyQt6 import QtWidgets, QtGui, QtCore
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from PyQt6.QtCore import *

import urllib
import datetime
import json
from pathlib import Path

import copy

from modules.PyQt.Tabs.구매.MRP.table_main import Table_Main
from modules.PyQt.User.object_value import Object_Get_Value, Object_Set_Value, Object_Diable_Edit, Object_ReadOnly
from modules.PyQt.component.combo_lineedit import Combo_LineEdit, 고객사_Widget, 구분_Widget,생산형태_Widget
import traceback
from modules.logging_config import get_plugin_logger



# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class 개별_Wid(QWidget):
	def __init__(self, parent:QWidget|None=None):
		super().__init__(parent)
		self.dataObj = {}
		self.tableView_Wid_appDBdatas =[]
		

	def UI(self):
		self.setObjectName("개별_mrp")
		self.resize(1499, 1085)
		self.vLayout_Main = QtWidgets.QVBoxLayout(self)
		self.vLayout_Main.setObjectName("vLayout_Main")
		self.frame_Head = QtWidgets.QFrame(self)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_Head.sizePolicy().hasHeightForWidth())
		self.frame_Head.setSizePolicy(sizePolicy)
		self.frame_Head.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_Head.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_Head.setObjectName("frame_Head")
		self.hLayout_Frame_Head = QtWidgets.QHBoxLayout(self.frame_Head)
		self.hLayout_Frame_Head.setObjectName("hLayout_Frame_Head")
		self.frame_28 = QtWidgets.QFrame(self.frame_Head)
		self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_28.setObjectName("frame_28")
		self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_28)
		self.verticalLayout_19.setContentsMargins(-1, 0, -1, 0)
		self.verticalLayout_19.setObjectName("verticalLayout_19")
		self.formLayout_10 = QtWidgets.QFormLayout()
		self.formLayout_10.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.formLayout_10.setVerticalSpacing(0)
		self.formLayout_10.setObjectName("formLayout_10")
		self.label = QtWidgets.QLabel(self.frame_28)
		self.label.setObjectName("label")
		self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
		self.comboBox_Line_Gogaek = 고객사_Widget(self.frame_28)
		self.comboBox_Line_Gogaek._render()
		self.comboBox_Line_Gogaek.setObjectName("comboBox_Line_Gogaek")
		self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_Line_Gogaek)
		self.label_21 = QtWidgets.QLabel(self.frame_28)
		self.label_21.setObjectName("label_21")
		self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
		self.comboBox_line_Gubun = 구분_Widget(self.frame_28)
		self.comboBox_line_Gubun._render()
		self.comboBox_line_Gubun.setObjectName("comboBox_line_Gubun")
		self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_line_Gubun)
		self.verticalLayout_19.addLayout(self.formLayout_10)
		self.hLayout_Frame_Head.addWidget(self.frame_28)
		self.frame_5 = QtWidgets.QFrame(self.frame_Head)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(3)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
		self.frame_5.setSizePolicy(sizePolicy)
		self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_5.setObjectName("frame_5")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
		self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
		self.verticalLayout_5.setSpacing(0)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.formLayout_3 = QtWidgets.QFormLayout()
		self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.formLayout_3.setObjectName("formLayout_3")
		self.label_5 = QtWidgets.QLabel(self.frame_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
		self.label_5.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_5.setFont(font)
		self.label_5.setAlignment(QtCore.Qt.AlignCenter)
		self.label_5.setObjectName("label_5")
		self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
		self.lineEdit_Job_name = QtWidgets.QLineEdit(self.frame_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(2)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit_Job_name.sizePolicy().hasHeightForWidth())
		self.lineEdit_Job_name.setSizePolicy(sizePolicy)
		self.lineEdit_Job_name.setObjectName("lineEdit_Job_name")
		self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Job_name)
		self.label_8 = QtWidgets.QLabel(self.frame_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
		self.label_8.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_8.setFont(font)
		self.label_8.setAlignment(QtCore.Qt.AlignCenter)
		self.label_8.setObjectName("label_8")
		self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
		self.lineEdit_Proj_No = QtWidgets.QLineEdit(self.frame_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(2)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit_Proj_No.sizePolicy().hasHeightForWidth())
		self.lineEdit_Proj_No.setSizePolicy(sizePolicy)
		self.lineEdit_Proj_No.setObjectName("lineEdit_Proj_No")
		self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Proj_No)
		self.verticalLayout_5.addLayout(self.formLayout_3)
		self.hLayout_Frame_Head.addWidget(self.frame_5)
		self.frame_6 = QtWidgets.QFrame(self.frame_Head)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
		self.frame_6.setSizePolicy(sizePolicy)
		self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_6.setObjectName("frame_6")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
		self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.formLayout_2 = QtWidgets.QFormLayout()
		self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.formLayout_2.setObjectName("formLayout_2")
		self.label_7 = QtWidgets.QLabel(self.frame_6)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
		self.label_7.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_7.setFont(font)
		self.label_7.setAlignment(QtCore.Qt.AlignCenter)
		self.label_7.setObjectName("label_7")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
		self.spinBox_Daesu = QtWidgets.QSpinBox(self.frame_6)
		self.spinBox_Daesu.setObjectName("spinBox_Daesu")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_Daesu)
		self.label_6 = QtWidgets.QLabel(self.frame_6)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
		self.label_6.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_6.setFont(font)
		self.label_6.setAlignment(QtCore.Qt.AlignCenter)
		self.label_6.setObjectName("label_6")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
		self.spinBox_chongsurang = QtWidgets.QSpinBox(self.frame_6)
		self.spinBox_chongsurang.setObjectName("spinBox_chongsurang")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_chongsurang)
		self.verticalLayout_6.addLayout(self.formLayout_2)
		self.hLayout_Frame_Head.addWidget(self.frame_6)
		self.frame_29 = QtWidgets.QFrame(self.frame_Head)
		self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_29.setObjectName("frame_29")
		self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_29)
		self.verticalLayout_23.setObjectName("verticalLayout_23")

		self.lcd_Total_HTM = QtWidgets.QLCDNumber(self.frame_29)
		font = QtGui.QFont()
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		self.lcd_Total_HTM.setFont(font)
		self.lcd_Total_HTM.setObjectName("lcd_Total_HTM")
		self.verticalLayout_23.addWidget(self.lcd_Total_HTM)
		self.hLayout_Frame_Head.addWidget(self.frame_29)
		self.frame_9 = QtWidgets.QFrame(self.frame_Head)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
		self.frame_9.setSizePolicy(sizePolicy)
		self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_9.setObjectName("frame_9")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
		self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.formLayout_6 = QtWidgets.QFormLayout()
		self.formLayout_6.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.formLayout_6.setObjectName("formLayout_6")
		self.dateEdit_Produce_3 = QtWidgets.QDateEdit(self.frame_9)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.dateEdit_Produce_3.sizePolicy().hasHeightForWidth())
		self.dateEdit_Produce_3.setSizePolicy(sizePolicy)
		self.dateEdit_Produce_3.setObjectName("dateEdit_Produce_3")
		self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_Produce_3)
		self.label_13 = QtWidgets.QLabel(self.frame_9)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
		self.label_13.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_13.setFont(font)
		self.label_13.setAlignment(QtCore.Qt.AlignCenter)
		self.label_13.setObjectName("label_13")
		self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
		self.dateEdit_Order_3 = QtWidgets.QDateEdit(self.frame_9)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.dateEdit_Order_3.sizePolicy().hasHeightForWidth())
		self.dateEdit_Order_3.setSizePolicy(sizePolicy)
		self.dateEdit_Order_3.setObjectName("dateEdit_Order_3")
		self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_Order_3)
		self.label_14 = QtWidgets.QLabel(self.frame_9)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
		self.label_14.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_14.setFont(font)
		self.label_14.setAlignment(QtCore.Qt.AlignCenter)
		self.label_14.setObjectName("label_14")
		self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
		self.verticalLayout_3.addLayout(self.formLayout_6)
		self.hLayout_Frame_Head.addWidget(self.frame_9)
		self.frame_8 = QtWidgets.QFrame(self.frame_Head)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
		self.frame_8.setSizePolicy(sizePolicy)
		self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_8.setObjectName("frame_8")
		self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
		self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.formLayout = QtWidgets.QFormLayout()
		self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.formLayout.setObjectName("formLayout")
		self.label_3 = QtWidgets.QLabel(self.frame_8)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_3.setFont(font)
		self.label_3.setAlignment(QtCore.Qt.AlignCenter)
		self.label_3.setObjectName("label_3")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
		self.label_4 = QtWidgets.QLabel(self.frame_8)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
		self.label_4.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_4.setFont(font)
		self.label_4.setAlignment(QtCore.Qt.AlignCenter)
		self.label_4.setObjectName("label_4")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
		self.lineEdit_Name = QtWidgets.QLineEdit(self.frame_8)
		self.lineEdit_Name.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit_Name.sizePolicy().hasHeightForWidth())
		self.lineEdit_Name.setSizePolicy(sizePolicy)
		self.lineEdit_Name.setObjectName("lineEdit_Name")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
		self.spinBox_Chasu = QtWidgets.QSpinBox(self.frame_8)
		self.spinBox_Chasu.setObjectName("spinBox_Chasu")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_Chasu)
		self.verticalLayout_8.addLayout(self.formLayout)
		self.hLayout_Frame_Head.addWidget(self.frame_8)
		self.frame_7 = QtWidgets.QFrame(self.frame_Head)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
		self.frame_7.setSizePolicy(sizePolicy)
		self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_7.setObjectName("frame_7")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
		self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.formLayout_4 = QtWidgets.QFormLayout()
		self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.formLayout_4.setObjectName("formLayout_4")
		self.dateEdit_Produce = QtWidgets.QDateEdit(self.frame_7)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.dateEdit_Produce.sizePolicy().hasHeightForWidth())
		self.dateEdit_Produce.setSizePolicy(sizePolicy)
		self.dateEdit_Produce.setObjectName("dateEdit_Produce")
		self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_Produce)
		self.label_10 = QtWidgets.QLabel(self.frame_7)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
		self.label_10.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_10.setFont(font)
		self.label_10.setAlignment(QtCore.Qt.AlignCenter)
		self.label_10.setObjectName("label_10")
		self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
		self.dateEdit_Order = QtWidgets.QDateEdit(self.frame_7)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.dateEdit_Order.sizePolicy().hasHeightForWidth())
		self.dateEdit_Order.setSizePolicy(sizePolicy)
		self.dateEdit_Order.setObjectName("dateEdit_Order")
		self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_Order)
		self.label_9 = QtWidgets.QLabel(self.frame_7)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
		self.label_9.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("HY견고딕")
		font.setPointSize(12)
		self.label_9.setFont(font)
		self.label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.label_9.setObjectName("label_9")
		self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
		self.verticalLayout_4.addLayout(self.formLayout_4)
		self.hLayout_Frame_Head.addWidget(self.frame_7)
		self.vLayout_Main.addWidget(self.frame_Head)
		self.frame_Table = QtWidgets.QFrame(self)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.frame_Table.sizePolicy().hasHeightForWidth())
		self.frame_Table.setSizePolicy(sizePolicy)
		self.frame_Table.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_Table.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_Table.setObjectName("frame_Table")
		self.vLayout_Frame_Table = QtWidgets.QVBoxLayout(self.frame_Table)
		self.vLayout_Frame_Table.setObjectName("vLayout_Frame_Table")

		self.tableView_Wid = Table_Main(self.frame_Table)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.tableView_Wid.sizePolicy().hasHeightForWidth())
		self.tableView_Wid.setSizePolicy(sizePolicy)
		self.tableView_Wid.setObjectName("tableView")
		self.vLayout_Frame_Table.addWidget(self.tableView_Wid)

		self.vLayout_Main.addWidget(self.frame_Table)

	def retranslateUi(self):        
		self.label.setText( "고객사" )
		self.label_21.setText( "구분" )
		self.label_5.setText( "Job-name" )
		self.label_8.setText( "Proj. No" )
		self.label_7.setText( "총수량" )
		self.label_6.setText( "대 수" )
		self.lcd_Total_HTM.setToolTip( "JAMB 제외된 HTM수량입니다" )
		self.label_13.setText( "소재발주일" )
		self.label_14.setText( "납기일" )
		self.label_3.setText( "차수" )
		self.label_4.setText( "작성자" )
		self.label_10.setText( "소재발주일" )
		self.label_9.setText( "생산지시일" )

	def _init_Input_Dict(self):
		""" UI 완료 후 초기화 진행 : 생산지시_form에서 일부 copy """
		self.inputDict = {
			### HTM
			'job_name' : self.lineEdit_Job_name,
			'proj_No' : self.lineEdit_Proj_No,
			'총수량' : self.spinBox_chongsurang,
			'지시수량' : self.spinBox_Daesu,
			'차수' : self.spinBox_Chasu,
			'작성자' : self.lineEdit_Name,
			'생산지시일' : self.dateEdit_Produce,
			'소재발주일' : self.dateEdit_Order,
			'구분' : self.comboBox_line_Gubun,
			'고객사' : self.comboBox_Line_Gogaek,
		}

		self.inputType = self.inputDict

	def _render_from_dataObj(self):
		if not self.dataObj : return
		for key, value in self.dataObj.items():
			if isinstance( value, str|int|float) and key in self.inputDict.keys():
				Object_ReadOnly(self.inputDict[key], value )
		total_count = 0
		for obj in self.tableView_Wid_appDBdatas:
			total_count += obj.get('수량', 0)
		self.lcd_Total_HTM.display(total_count)
		self.lcd_Total_HTM.setStyleSheet('background-color:yellow;color:black;font-size:32px;')

	def run(self):
		self.UI()
		self.retranslateUi()
		self._init_Input_Dict()

		self.tableView_Wid.app_DB_data = self.tableView_Wid_appDBdatas
		self.tableView_Wid.run()
		self._render_from_dataObj()
		self.show()
