import sys
from PyQt6 import QtWidgets, QtGui, QtCore
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from PyQt6.QtCore import *

import urllib
import datetime
import json
from pathlib import Path

import copy
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class 종합_Wid(QWidget):
    def __init__(self, parent:QWidget|None=None):
        super().__init__(parent)
        

    def UI(self):
        self.setObjectName("종합_Wid")
        self.resize(1410, 983)
        self.vLayout_main = QtWidgets.QVBoxLayout(self)
        self.vLayout_main.setObjectName("vLayout_main")
        self.frame_head = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_head.sizePolicy().hasHeightForWidth())
        self.frame_head.setSizePolicy(sizePolicy)
        self.frame_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_head.setObjectName("frame_head")
        self.hLayout_Frame_Head = QtWidgets.QHBoxLayout(self.frame_head)
        self.hLayout_Frame_Head.setObjectName("hLayout_Frame_Head")
        self.frame_30 = QtWidgets.QFrame(self.frame_head)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_20.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_11.setVerticalSpacing(0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.spinBox = QtWidgets.QSpinBox(self.frame_30)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.frame_30)
        self.label_2.setObjectName("label_2")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_20.addLayout(self.formLayout_11)
        self.hLayout_Frame_Head.addWidget(self.frame_30)
        self.frame_10 = QtWidgets.QFrame(self.frame_head)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setObjectName("formLayout_7")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_10)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("HY견고딕")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.verticalLayout_7.addLayout(self.formLayout_7)
        self.hLayout_Frame_Head.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_head)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_11)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setObjectName("label_17")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_11)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.verticalLayout_9.addLayout(self.formLayout_8)
        self.hLayout_Frame_Head.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_head)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.Label_Baljuil = QtWidgets.QLabel(self.frame_12)
        self.Label_Baljuil.setObjectName("Label_Baljuil")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_Baljuil)
        self.DateEdit = QtWidgets.QDateEdit(self.frame_12)
        self.DateEdit.setObjectName("DateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.hLayout_Frame_Head.addWidget(self.frame_12)
        self.vLayout_main.addWidget(self.frame_head)

        self.frame_Table = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_Table.sizePolicy().hasHeightForWidth())
        self.frame_Table.setSizePolicy(sizePolicy)
        self.frame_Table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Table.setObjectName("frame_Table")
        self.vLayout_Frame_Table = QtWidgets.QVBoxLayout(self.frame_Table)
        self.vLayout_Frame_Table.setObjectName("vLayout_Frame_Table")
        self.tableView_2 = QtWidgets.QTableView(self.frame_Table)
        self.tableView_2.setObjectName("tableView_2")
        self.vLayout_Frame_Table.addWidget(self.tableView_2)
        self.vLayout_main.addWidget(self.frame_Table)

    def retranslateUi(self):       
        self.setWindowTitle("종합 Summary")
        self.label_2.setText( "현장수")
        self.label_15.setText( "현장 리스트")
        self.label_16.setText( "총 EL수")
        self.label_17.setText( "총 층수")
        self.Label_Baljuil.setText( "발주일")
        # self.label_19.setText( "소재발주일")
        # self.label_20.setText( "예상입고일")

    def run(self):
        self.UI()
        self.retranslateUi()

        self.show()
