# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/sub_window/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 700))
        Form.setMaximumSize(QtCore.QSize(600, 700))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(64, 32, 64, 32)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/sw_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit_MailID = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_MailID.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_MailID.setObjectName("lineEdit_MailID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_MailID)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_Password)
        self.verticalLayout.addLayout(self.formLayout)
        self.ck_box_autoLogin = QtWidgets.QCheckBox(parent=Form)
        self.ck_box_autoLogin.setObjectName("ck_box_autoLogin")
        self.verticalLayout.addWidget(self.ck_box_autoLogin)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.FR_Btns = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FR_Btns.sizePolicy().hasHeightForWidth())
        self.FR_Btns.setSizePolicy(sizePolicy)
        self.FR_Btns.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.FR_Btns.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FR_Btns.setObjectName("FR_Btns")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FR_Btns)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.PB_save = QtWidgets.QPushButton(parent=self.FR_Btns)
        self.PB_save.setEnabled(False)
        self.PB_save.setObjectName("PB_save")
        self.horizontalLayout.addWidget(self.PB_save)
        self.PB_cancel = QtWidgets.QPushButton(parent=self.FR_Btns)
        self.PB_cancel.setSizeIncrement(QtCore.QSize(600, 400))
        self.PB_cancel.setBaseSize(QtCore.QSize(600, 400))
        self.PB_cancel.setObjectName("PB_cancel")
        self.horizontalLayout.addWidget(self.PB_cancel)
        self.verticalLayout.addWidget(self.FR_Btns)

        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Log in"))
        self.label_2.setText(_translate("Form", "Mail ID"))
        self.lineEdit_MailID.setPlaceholderText(_translate("Form", "회사 mail id를 넣으세요"))
        self.label_3.setText(_translate("Form", "Password"))
        self.ck_box_autoLogin.setText(_translate("Form", "7일간 자동 Login 합니다"))
        self.PB_save.setText(_translate("Form", "Login"))
        self.PB_cancel.setText(_translate("Form", "Cancel"))
