# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/HR평가/dialog/ui/dialog_역량평가.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Dialog_Yokyang(object):
    def setupUi(self, Dialog_Yokyang):
        Dialog_Yokyang.setObjectName("Dialog_Yokyang")
        Dialog_Yokyang.resize(1123, 535)
        self.listWidget_before = QtWidgets.QListWidget(parent=Dialog_Yokyang)
        self.listWidget_before.setGeometry(QtCore.QRect(50, 70, 421, 431))
        self.listWidget_before.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_before.setObjectName("listWidget_before")
        self.listWidget_after = QtWidgets.QListWidget(parent=Dialog_Yokyang)
        self.listWidget_after.setGeometry(QtCore.QRect(680, 70, 421, 431))
        self.listWidget_after.setDefaultDropAction(QtCore.Qt.DropAction.CopyAction)
        self.listWidget_after.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_after.setObjectName("listWidget_after")
        self.PB_Select = QtWidgets.QPushButton(parent=Dialog_Yokyang)
        self.PB_Select.setGeometry(QtCore.QRect(540, 130, 89, 25))
        self.PB_Select.setObjectName("PB_Select")
        self.PB_Unselect = QtWidgets.QPushButton(parent=Dialog_Yokyang)
        self.PB_Unselect.setGeometry(QtCore.QRect(540, 340, 89, 25))
        self.PB_Unselect.setObjectName("PB_Unselect")
        self.PB_Save = QtWidgets.QPushButton(parent=Dialog_Yokyang)
        self.PB_Save.setGeometry(QtCore.QRect(1010, 20, 89, 25))
        self.PB_Save.setObjectName("PB_Save")

        self.retranslateUi(Dialog_Yokyang)
        # QtCore.QMetaObject.connectSlotsByName(Dialog_Yokyang)

    def retranslateUi(self, Dialog_Yokyang):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Yokyang.setWindowTitle(_translate("Dialog_Yokyang", "역량평가 항목"))
        self.PB_Select.setText(_translate("Dialog_Yokyang", "Select"))
        self.PB_Unselect.setText(_translate("Dialog_Yokyang", "UnSelect"))
        self.PB_Save.setText(_translate("Dialog_Yokyang", "저장"))
