# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/망관리/ui/tab_망관리_album.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab_App(object):
    def setupUi(self, Tab_App):
        Tab_App.setObjectName("Tab_App")
        Tab_App.resize(1345, 853)
        self.vLayout = QtWidgets.QVBoxLayout(Tab_App)
        self.vLayout.setObjectName("vLayout")
        self.frame_info = QtWidgets.QFrame(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy)
        self.frame_info.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_info = QtWidgets.QPushButton(parent=self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_info.sizePolicy().hasHeightForWidth())
        self.pb_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.pb_info.setFont(font)
        self.pb_info.setObjectName("pb_info")
        self.horizontalLayout_4.addWidget(self.pb_info)
        spacerItem = QtWidgets.QSpacerItem(1238, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.PB_Form_New = QtWidgets.QPushButton(parent=self.frame_info)
        self.PB_Form_New.setObjectName("PB_Form_New")
        self.horizontalLayout_4.addWidget(self.PB_Form_New)
        self.vLayout.addWidget(self.frame_info)
        self.Wid_Search_for = Wid_Search_for(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wid_Search_for.sizePolicy().hasHeightForWidth())
        self.Wid_Search_for.setSizePolicy(sizePolicy)
        self.Wid_Search_for.setObjectName("Wid_Search_for")
        self.vLayout.addWidget(self.Wid_Search_for)
        self.frame_album_contents = QtWidgets.QFrame(parent=Tab_App)
        self.frame_album_contents.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_album_contents.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_album_contents.setObjectName("frame_album_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_album_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.Wid_album_5 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_5.setObjectName("Wid_album_5")
        self.gridLayout.addWidget(self.Wid_album_5, 1, 0, 1, 1)
        self.Wid_album_3 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_3.setObjectName("Wid_album_3")
        self.gridLayout.addWidget(self.Wid_album_3, 0, 3, 1, 1)
        self.Wid_album_2 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_2.setObjectName("Wid_album_2")
        self.gridLayout.addWidget(self.Wid_album_2, 0, 2, 1, 1)
        self.Wid_album_0 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_0.setObjectName("Wid_album_0")
        self.gridLayout.addWidget(self.Wid_album_0, 0, 0, 1, 1)
        self.Wid_album_1 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_1.setObjectName("Wid_album_1")
        self.gridLayout.addWidget(self.Wid_album_1, 0, 1, 1, 1)
        self.Wid_album_4 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_4.setObjectName("Wid_album_4")
        self.gridLayout.addWidget(self.Wid_album_4, 0, 4, 1, 1)
        self.Wid_album_10 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_10.setObjectName("Wid_album_10")
        self.gridLayout.addWidget(self.Wid_album_10, 2, 0, 1, 1)
        self.Wid_album_6 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_6.setObjectName("Wid_album_6")
        self.gridLayout.addWidget(self.Wid_album_6, 1, 1, 1, 1)
        self.Wid_album_7 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_7.setObjectName("Wid_album_7")
        self.gridLayout.addWidget(self.Wid_album_7, 1, 2, 1, 1)
        self.Wid_album_8 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_8.setObjectName("Wid_album_8")
        self.gridLayout.addWidget(self.Wid_album_8, 1, 3, 1, 1)
        self.Wid_album_9 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_9.setObjectName("Wid_album_9")
        self.gridLayout.addWidget(self.Wid_album_9, 1, 4, 1, 1)
        self.Wid_album_11 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_11.setObjectName("Wid_album_11")
        self.gridLayout.addWidget(self.Wid_album_11, 2, 1, 1, 1)
        self.Wid_album_12 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_12.setObjectName("Wid_album_12")
        self.gridLayout.addWidget(self.Wid_album_12, 2, 2, 1, 1)
        self.Wid_album_13 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_13.setObjectName("Wid_album_13")
        self.gridLayout.addWidget(self.Wid_album_13, 2, 3, 1, 1)
        self.Wid_album_14 = Wid_album_망단위(parent=self.frame_album_contents)
        self.Wid_album_14.setObjectName("Wid_album_14")
        self.gridLayout.addWidget(self.Wid_album_14, 2, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.vLayout.addWidget(self.frame_album_contents)

        self.retranslateUi(Tab_App)
        # QtCore.QMetaObject.connectSlotsByName(Tab_App)

    def retranslateUi(self, Tab_App):
        _translate = QtCore.QCoreApplication.translate
        Tab_App.setWindowTitle(_translate("Tab_App", "Form"))
        self.pb_info.setText(_translate("Tab_App", "?"))
        self.PB_Form_New.setText(_translate("Tab_App", "Form신규"))
from modules.PyQt.Tabs.망관리.components.Wid_search_for_망관리_album import Wid_Search_for
from modules.PyQt.Tabs.망관리.widget.Wid_album_망단위 import Wid_album_망단위
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


