# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/일일업무/ui/dlg_file_upload_전기사용량.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Dialog_fileUpload(object):
    def setupUi(self, Dialog_fileUpload):
        Dialog_fileUpload.setObjectName("Dialog_fileUpload")
        Dialog_fileUpload.resize(552, 186)
        Dialog_fileUpload.setToolTip("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_fileUpload)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog_fileUpload)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:yellow")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.PB_Save = QtWidgets.QPushButton(parent=self.frame)
        self.PB_Save.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_Save.sizePolicy().hasHeightForWidth())
        self.PB_Save.setSizePolicy(sizePolicy)
        self.PB_Save.setObjectName("PB_Save")
        self.horizontalLayout_3.addWidget(self.PB_Save)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_HI = QtWidgets.QFrame(parent=Dialog_fileUpload)
        self.frame_HI.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_HI.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_HI.setObjectName("frame_HI")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_HI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_HI = QtWidgets.QPushButton(parent=self.frame_HI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_HI.sizePolicy().hasHeightForWidth())
        self.PB_HI.setSizePolicy(sizePolicy)
        self.PB_HI.setObjectName("PB_HI")
        self.horizontalLayout.addWidget(self.PB_HI)
        self.label_HI = QtWidgets.QLabel(parent=self.frame_HI)
        self.label_HI.setStyleSheet("background-color:black;color:yellow")
        self.label_HI.setObjectName("label_HI")
        self.horizontalLayout.addWidget(self.label_HI)
        self.verticalLayout.addWidget(self.frame_HI)
        self.frame_PO = QtWidgets.QFrame(parent=Dialog_fileUpload)
        self.frame_PO.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_PO.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_PO.setObjectName("frame_PO")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_PO)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_PO = QtWidgets.QPushButton(parent=self.frame_PO)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_PO.sizePolicy().hasHeightForWidth())
        self.PB_PO.setSizePolicy(sizePolicy)
        self.PB_PO.setObjectName("PB_PO")
        self.horizontalLayout_2.addWidget(self.PB_PO)
        self.label_PO = QtWidgets.QLabel(parent=self.frame_PO)
        self.label_PO.setStyleSheet("background-color:black;color:yellow")
        self.label_PO.setObjectName("label_PO")
        self.horizontalLayout_2.addWidget(self.label_PO)
        self.verticalLayout.addWidget(self.frame_PO)

        self.retranslateUi(Dialog_fileUpload)
        # QtCore.QMetaObject.connectSlotsByName(Dialog_fileUpload)

    def retranslateUi(self, Dialog_fileUpload):
        _translate = QtCore.QCoreApplication.translate
        Dialog_fileUpload.setWindowTitle(_translate("Dialog_fileUpload", "전기사용량_파일업로드"))
        self.label.setText(_translate("Dialog_fileUpload", "HI, PO 모두 파일 등록이 되어야지 저장이 가능합니다."))
        self.PB_Save.setText(_translate("Dialog_fileUpload", "저장"))
        self.PB_HI.setText(_translate("Dialog_fileUpload", "HI"))
        self.label_HI.setText(_translate("Dialog_fileUpload", "HI"))
        self.PB_PO.setText(_translate("Dialog_fileUpload", "PO"))
        self.label_PO.setText(_translate("Dialog_fileUpload", "PO"))
