# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/생산지시서/dialog/ui/생산지지서_form_empty_tab.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(922, 870)
        self.vLayout_main = QtWidgets.QVBoxLayout(Form)
        self.vLayout_main.setObjectName("vLayout_main")
        self.Wid_imageViewer = ImageViewer(parent=Form)
        self.Wid_imageViewer.setObjectName("Wid_imageViewer")
        self.vLayout_main.addWidget(self.Wid_imageViewer)

        self.retranslateUi(Form)
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from modules.PyQt.compoent_v2.imageViewer.imageviwer import ImageViewer
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


