# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/dialog/textedit/ui/dialog_rich_text_edit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Dialog_textEdit(object):
    def setupUi(self, Dialog_textEdit):
        Dialog_textEdit.setObjectName("Dialog_textEdit")
        Dialog_textEdit.resize(931, 725)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_textEdit)
        self.buttonBox.setGeometry(QtCore.QRect(500, 590, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog_textEdit)
        self.textEdit.setGeometry(QtCore.QRect(40, 70, 381, 431))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog_textEdit)
        self.textBrowser.setGeometry(QtCore.QRect(490, 70, 411, 421))
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(parent=Dialog_textEdit)
        self.label.setGeometry(QtCore.QRect(190, 40, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog_textEdit)
        self.label_2.setGeometry(QtCore.QRect(670, 40, 67, 17))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_textEdit)
        self.buttonBox.accepted.connect(Dialog_textEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_textEdit.reject) # type: ignore
        # QtCore.QMetaObject.connectSlotsByName(Dialog_textEdit)

    def retranslateUi(self, Dialog_textEdit):
        _translate = QtCore.QCoreApplication.translate
        Dialog_textEdit.setWindowTitle(_translate("Dialog_textEdit", "Dialog"))
        self.label.setText(_translate("Dialog_textEdit", "원본"))
        self.label_2.setText(_translate("Dialog_textEdit", "Preview"))
