# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/dialog/page_help_tb/ui/dialog_page_info.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Dialog_textEdit(object):
    def setupUi(self, Dialog_textEdit):
        Dialog_textEdit.setObjectName("Dialog_textEdit")
        Dialog_textEdit.resize(586, 621)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_textEdit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog_textEdit)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(" background-color:black;color:yellow")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog_textEdit)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.frame = QtWidgets.QFrame(parent=Dialog_textEdit)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_ok = QtWidgets.QPushButton(parent=self.frame)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout.addWidget(self.pb_ok)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog_textEdit)
        # QtCore.QMetaObject.connectSlotsByName(Dialog_textEdit)

    def retranslateUi(self, Dialog_textEdit):
        _translate = QtCore.QCoreApplication.translate
        Dialog_textEdit.setWindowTitle(_translate("Dialog_textEdit", "Dialog"))
        self.label.setText(_translate("Dialog_textEdit", "이 APP에 대한 간단한 설명입니다."))
        self.pb_ok.setText(_translate("Dialog_textEdit", "확인"))
