# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/샘플관리/ui/tab_샘플관리_관리.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab_App(object):
    def setupUi(self, Tab_App):
        Tab_App.setObjectName("Tab_App")
        Tab_App.resize(1345, 853)
        self.verticalLayout = QtWidgets.QVBoxLayout(Tab_App)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_info = QtWidgets.QFrame(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy)
        self.frame_info.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_info = QtWidgets.QPushButton(parent=self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_info.sizePolicy().hasHeightForWidth())
        self.pb_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.pb_info.setFont(font)
        self.pb_info.setObjectName("pb_info")
        self.horizontalLayout.addWidget(self.pb_info)
        self.label_list = QtWidgets.QLabel(parent=self.frame_info)
        self.label_list.setObjectName("label_list")
        self.horizontalLayout.addWidget(self.label_list)
        self.label_target = QtWidgets.QLabel(parent=self.frame_info)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_target.setFont(font)
        self.label_target.setStyleSheet("background-color:black;color:yellow;")
        self.label_target.setObjectName("label_target")
        self.horizontalLayout.addWidget(self.label_target)
        spacerItem = QtWidgets.QSpacerItem(1238, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_info)
        self.Wid_Search_for = Wid_Search_for(parent=Tab_App)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wid_Search_for.sizePolicy().hasHeightForWidth())
        self.Wid_Search_for.setSizePolicy(sizePolicy)
        self.Wid_Search_for.setObjectName("Wid_Search_for")
        self.verticalLayout.addWidget(self.Wid_Search_for)
        self.Wid_Table = Wid_Table_for_샘플관리_관리(parent=Tab_App)
        self.Wid_Table.setObjectName("Wid_Table")
        self.verticalLayout.addWidget(self.Wid_Table)

        self.retranslateUi(Tab_App)
        # QtCore.QMetaObject.connectSlotsByName(Tab_App)

    def retranslateUi(self, Tab_App):
        _translate = QtCore.QCoreApplication.translate
        Tab_App.setWindowTitle(_translate("Tab_App", "Form"))
        self.pb_info.setText(_translate("Tab_App", "?"))
        self.label_list.setText(_translate("Tab_App", "대상차량"))
        self.label_target.setText(_translate("Tab_App", "TextLabel"))
from modules.PyQt.Tabs.샘플관리.components.Wid_search_for_관리 import Wid_Search_for
from modules.PyQt.Tabs.샘플관리.tables.table_샘플관리_관리 import Wid_Table_for_샘플관리_관리
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


