# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkt/development/python/gui/Shinwoo_APP_ver0.09/modules/PyQt6/component/search/search_compenet.ui'
#
# Created by: PyQt6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1178, 66)
        self.vLayout_main = QtWidgets.QVBoxLayout(Form)
        self.vLayout_main.setObjectName("vLayout_main")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_Gijun = Combo_작지_dashboard_날짜(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Gijun.sizePolicy().hasHeightForWidth())
        self.comboBox_Gijun.setSizePolicy(sizePolicy)
        self.comboBox_Gijun.setObjectName("comboBox_Gijun")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_Gijun)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_Gogaek = Combo_작지_dashboard_고객사(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Gogaek.sizePolicy().hasHeightForWidth())
        self.comboBox_Gogaek.setSizePolicy(sizePolicy)
        self.comboBox_Gogaek.setObjectName("comboBox_Gogaek")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_Gogaek)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_Gubun = Combo_작지_dashboard_구분(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Gubun.sizePolicy().hasHeightForWidth())
        self.comboBox_Gubun.setSizePolicy(sizePolicy)
        self.comboBox_Gubun.setObjectName("comboBox_Gubun")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_Gubun)
        self.horizontalLayout.addLayout(self.formLayout_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateEdit_From = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_From.setCalendarPopup(True)
        self.dateEdit_From.setObjectName("dateEdit_From")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_From)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dateEdit_To = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_To.setCalendarPopup(True)
        self.dateEdit_To.setObjectName("dateEdit_To")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_To)
        self.horizontalLayout.addLayout(self.formLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_Search = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_Search.sizePolicy().hasHeightForWidth())
        self.PB_Search.setSizePolicy(sizePolicy)
        self.PB_Search.setObjectName("PB_Search")
        self.horizontalLayout.addWidget(self.PB_Search)
        self.vLayout_main.addWidget(self.frame)

        self.retranslateUi(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "기준"))
        self.label_4.setText(_translate("Form", "고객사"))
        self.label_5.setText(_translate("Form", "구분"))
        self.label_2.setText(_translate("Form", "From 일자"))
        self.label_3.setText(_translate("Form", "To 일자"))
        self.PB_Search.setText(_translate("Form", "Run"))
from modules.PyQt.component.combo_custom import Combo_작지_dashboard_고객사, Combo_작지_dashboard_구분, Combo_작지_dashboard_날짜
import traceback
from modules.logging_config import get_plugin_logger

# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()


