# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/component/file/ui/file_listwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 204)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.fr_btn_container = QtWidgets.QFrame(parent=Form)
        self.fr_btn_container.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fr_btn_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_btn_container.setObjectName("fr_btn_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_btn_container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_Upload = QtWidgets.QPushButton(parent=self.fr_btn_container)
        self.PB_Upload.setObjectName("PB_Upload")
        self.horizontalLayout.addWidget(self.PB_Upload)
        self.PB_Delete = QtWidgets.QPushButton(parent=self.fr_btn_container)
        self.PB_Delete.setObjectName("PB_Delete")
        self.horizontalLayout.addWidget(self.PB_Delete)
        self.verticalLayout.addWidget(self.fr_btn_container)

        self.retranslateUi(Form)
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "File List"))
        self.PB_Upload.setText(_translate("Form", "File Upload"))
        self.PB_Delete.setText(_translate("Form", "File Delete"))
