# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/plugins/ui/search_common.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Search(object):
    def setupUi(self, Search):
        Search.setObjectName("Search")
        Search.resize(1378, 68)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Search.sizePolicy().hasHeightForWidth())
        Search.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Search)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_search = Custom_Search_LineEdit(parent=self.frame)
        self.le_search.setObjectName("le_search")
        self.horizontalLayout.addWidget(self.le_search)
        self.PB_Option = Custom_PB_Query(parent=self.frame)
        self.PB_Option.setObjectName("PB_Option")
        self.horizontalLayout.addWidget(self.PB_Option)
        self.frame_option = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_option.sizePolicy().hasHeightForWidth())
        self.frame_option.setSizePolicy(sizePolicy)
        self.frame_option.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_option.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_option.setObjectName("frame_option")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_option)
        self.horizontalLayout_2.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addWidget(self.frame_option)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.comboBox_pageSize = Custom_Combo_PageSize(parent=self.frame)
        self.comboBox_pageSize.setCurrentText("")
        self.comboBox_pageSize.setObjectName("comboBox_pageSize")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_pageSize)
        self.horizontalLayout.addLayout(self.formLayout_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_Search = Custom_PB_Query(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_Search.sizePolicy().hasHeightForWidth())
        self.PB_Search.setSizePolicy(sizePolicy)
        self.PB_Search.setObjectName("PB_Search")
        self.horizontalLayout.addWidget(self.PB_Search)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Search)
        # QtCore.QMetaObject.connectSlotsByName(Search)

    def retranslateUi(self, Search):
        _translate = QtCore.QCoreApplication.translate
        Search.setWindowTitle(_translate("Search", "Form"))
        self.label.setText(_translate("Search", "검색"))
        self.le_search.setPlaceholderText(_translate("Search", "공란이면 전체 조회"))
        self.PB_Option.setText(_translate("Search", "조회조건"))
        self.label_6.setText(_translate("Search", "PageSize"))
        self.PB_Search.setText(_translate("Search", "조회"))
from modules.PyQt.compoent_v2.custom_상속.custom_PB import Custom_PB_Query
from modules.PyQt.compoent_v2.custom_상속.custom_combo import Custom_Combo_PageSize
from modules.PyQt.compoent_v2.custom_상속.custom_lineEdit import Custom_Search_LineEdit
