# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/plugins/ui/table_head.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tableheader(object):
    def setupUi(self, tableheader):
        tableheader.setObjectName("tableheader")
        tableheader.resize(1378, 61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tableheader.sizePolicy().hasHeightForWidth())
        tableheader.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(tableheader)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(parent=tableheader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_update_time = QtWidgets.QLabel(parent=tableheader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_update_time.sizePolicy().hasHeightForWidth())
        self.label_update_time.setSizePolicy(sizePolicy)
        self.label_update_time.setStyleSheet("background-color:yellow;font-weight:bold;padding:5px, 0px;")
        self.label_update_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_update_time.setObjectName("label_update_time")
        self.horizontalLayout.addWidget(self.label_update_time)
        self.label_update_gap = QtWidgets.QLabel(parent=tableheader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_update_gap.sizePolicy().hasHeightForWidth())
        self.label_update_gap.setSizePolicy(sizePolicy)
        self.label_update_gap.setStyleSheet("font-weight:bold")
        self.label_update_gap.setObjectName("label_update_gap")
        self.horizontalLayout.addWidget(self.label_update_gap)
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(parent=tableheader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox_edit_mode = Combo_Select_Edit_Mode(parent=tableheader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_edit_mode.sizePolicy().hasHeightForWidth())
        self.comboBox_edit_mode.setSizePolicy(sizePolicy)
        self.comboBox_edit_mode.setObjectName("comboBox_edit_mode")
        self.horizontalLayout.addWidget(self.comboBox_edit_mode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.PB_save = Custom_PB_Query(parent=tableheader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_save.sizePolicy().hasHeightForWidth())
        self.PB_save.setSizePolicy(sizePolicy)
        self.PB_save.setObjectName("PB_save")
        self.horizontalLayout.addWidget(self.PB_save)

        self.retranslateUi(tableheader)
        # QtCore.QMetaObject.connectSlotsByName(tableheader)

    def retranslateUi(self, tableheader):
        _translate = QtCore.QCoreApplication.translate
        tableheader.setWindowTitle(_translate("tableheader", "Form"))
        self.label_7.setText(_translate("tableheader", "Data Update 시간"))
        self.label_update_time.setText(_translate("tableheader", "13:00:00"))
        self.label_update_gap.setText(_translate("tableheader", "(10분전)"))
        self.label_8.setText(_translate("tableheader", "편집모드"))
        self.PB_save.setText(_translate("tableheader", "Row 저장"))
from modules.PyQt.compoent_v2.custom_상속.custom_PB import Custom_PB_Query
from modules.PyQt.compoent_v2.custom_상속.custom_combo import Combo_Select_Edit_Mode
