# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/plugins/ui/table_config.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Wid_Table_Config(object):
    def setupUi(self, Wid_Table_Config):
        Wid_Table_Config.setObjectName("Wid_Table_Config")
        Wid_Table_Config.resize(1378, 30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Wid_Table_Config.sizePolicy().hasHeightForWidth())
        Wid_Table_Config.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Wid_Table_Config)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Wid_Table_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_display = QtWidgets.QLabel(parent=Wid_Table_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_display.sizePolicy().hasHeightForWidth())
        self.label_display.setSizePolicy(sizePolicy)
        self.label_display.setText("")
        self.label_display.setObjectName("label_display")
        self.horizontalLayout.addWidget(self.label_display)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_Row = QtWidgets.QPushButton(parent=Wid_Table_Config)
        self.PB_Row.setObjectName("PB_Row")
        self.horizontalLayout.addWidget(self.PB_Row)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.PB_Col = QtWidgets.QPushButton(parent=Wid_Table_Config)
        self.PB_Col.setObjectName("PB_Col")
        self.horizontalLayout.addWidget(self.PB_Col)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.PB_Cell = QtWidgets.QPushButton(parent=Wid_Table_Config)
        self.PB_Cell.setObjectName("PB_Cell")
        self.horizontalLayout.addWidget(self.PB_Cell)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.PB_save = Custom_PB_Query(parent=Wid_Table_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_save.sizePolicy().hasHeightForWidth())
        self.PB_save.setSizePolicy(sizePolicy)
        self.PB_save.setObjectName("PB_save")
        self.horizontalLayout.addWidget(self.PB_save)

        self.retranslateUi(Wid_Table_Config)
        # QtCore.QMetaObject.connectSlotsByName(Wid_Table_Config)

    def retranslateUi(self, Wid_Table_Config):
        _translate = QtCore.QCoreApplication.translate
        Wid_Table_Config.setWindowTitle(_translate("Wid_Table_Config", "Form"))
        self.label.setText(_translate("Wid_Table_Config", "환경설정 모드"))
        self.PB_Row.setText(_translate("Wid_Table_Config", "Row Menu"))
        self.PB_Col.setText(_translate("Wid_Table_Config", "Column Menu"))
        self.PB_Cell.setText(_translate("Wid_Table_Config", "Cell Menu"))
        self.PB_save.setText(_translate("Wid_Table_Config", "환경 저장"))
from modules.PyQt.compoent_v2.custom_상속.custom_PB import Custom_PB_Query
