# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/plugins/ui/tab_info.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab_Info(object):
    def setupUi(self, Tab_Info):
        Tab_Info.setObjectName("Tab_Info")
        Tab_Info.resize(1670, 27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tab_Info.sizePolicy().hasHeightForWidth())
        Tab_Info.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Tab_Info)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_info = QtWidgets.QPushButton(parent=Tab_Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_info.sizePolicy().hasHeightForWidth())
        self.pb_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.pb_info.setFont(font)
        self.pb_info.setObjectName("pb_info")
        self.horizontalLayout_2.addWidget(self.pb_info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(parent=Tab_Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setStyleSheet("background-color:black;color:yellow;font-weight:bold;")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.label_sub = QtWidgets.QLabel(parent=Tab_Info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sub.sizePolicy().hasHeightForWidth())
        self.label_sub.setSizePolicy(sizePolicy)
        self.label_sub.setText("")
        self.label_sub.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sub.setObjectName("label_sub")
        self.horizontalLayout_2.addWidget(self.label_sub)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.retranslateUi(Tab_Info)
        # QtCore.QMetaObject.connectSlotsByName(Tab_Info)

    def retranslateUi(self, Tab_Info):
        _translate = QtCore.QCoreApplication.translate
        Tab_Info.setWindowTitle(_translate("Tab_Info", "Form"))
        self.pb_info.setText(_translate("Tab_Info", "?"))
        self.label_title.setText(_translate("Tab_Info", "test"))
