# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/plugins/ui/tab_common_v2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab_Common(object):
    def setupUi(self, Tab_Common):
        #### ✅ 25-7-7 추가 : Tab_Common으로 baseTab을 주므로, objectName을 지정하지 않음.
        # Tab_Common.setObjectName("Tab_Common")
        Tab_Common.resize(1670, 853)
        self.verticalLayout = QtWidgets.QVBoxLayout(Tab_Common)
        self.verticalLayout.setObjectName("verticalLayout")
        self.v_info = QtWidgets.QVBoxLayout()
        self.v_info.setObjectName("v_info")
        self.wid_info = Wid_Info(parent=Tab_Common)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_info.sizePolicy().hasHeightForWidth())
        self.wid_info.setSizePolicy(sizePolicy)
        self.wid_info.setObjectName("wid_info")
        self.v_info.addWidget(self.wid_info)
        self.verticalLayout.addLayout(self.v_info)
        self.h_search = QtWidgets.QHBoxLayout()
        self.h_search.setObjectName("h_search")
        self.wid_search = Wid_Search_Common(parent=Tab_Common)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_search.sizePolicy().hasHeightForWidth())
        self.wid_search.setSizePolicy(sizePolicy)
        self.wid_search.setObjectName("wid_search")
        self.h_search.addWidget(self.wid_search)
        self.verticalLayout.addLayout(self.h_search)
        self.v_pagination = QtWidgets.QVBoxLayout()
        self.v_pagination.setObjectName("v_pagination")
        self.wid_pagination = Wid_Page_Common(parent=Tab_Common)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_pagination.sizePolicy().hasHeightForWidth())
        self.wid_pagination.setSizePolicy(sizePolicy)
        self.wid_pagination.setObjectName("wid_pagination")
        self.v_pagination.addWidget(self.wid_pagination)
        self.verticalLayout.addLayout(self.v_pagination)
        self.v_table = QtWidgets.QVBoxLayout()
        self.v_table.setObjectName("v_table")
        self.verticalLayout.addLayout(self.v_table)

        self.retranslateUi(Tab_Common)
        # QtCore.QMetaObject.connectSlotsByName(Tab_Common)

    def retranslateUi(self, Tab_Common):
        _translate = QtCore.QCoreApplication.translate
        Tab_Common.setWindowTitle(_translate("Tab_Common", "Form"))
from modules.PyQt.Tabs.plugins.ui.Wid_info import Wid_Info
from modules.PyQt.Tabs.plugins.ui.Wid_page_common import Wid_Page_Common
from modules.PyQt.Tabs.plugins.ui.Wid_search_common import Wid_Search_Common
