# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/Tabs/plugins/ui/tab_common_v2_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tab_Common(object):
    def setupUi(self, Tab_Common):
        Tab_Common.setObjectName("Tab_Common")
        Tab_Common.resize(1670, 853)
        self.verticalLayout = QtWidgets.QVBoxLayout(Tab_Common)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Tab_Common)
        # QtCore.QMetaObject.connectSlotsBeyName(Tab_Common)

    def retranslateUi(self, Tab_Common):
        _translate = QtCore.QCoreApplication.translate
        Tab_Common.setWindowTitle(_translate("Tab_Common", "Form"))
