# Form implementation generated from reading ui file '/home/kkt/development/python/PyQt6/sh_app/modules/PyQt/component/imageviewer/ui/wid_imagView.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_wid_imageViewer(object):
    def setupUi(self, wid_imageViewer):
        wid_imageViewer.setObjectName("wid_imageViewer")
        wid_imageViewer.resize(438, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(wid_imageViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_imageView = QtWidgets.QLabel(parent=wid_imageViewer)
        self.label_imageView.setScaledContents(False)
        self.label_imageView.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_imageView.setObjectName("label_imageView")
        self.verticalLayout.addWidget(self.label_imageView)

        self.retranslateUi(wid_imageViewer)
        # QtCore.QMetaObject.connectSlotsByName(wid_imageViewer)

    def retranslateUi(self, wid_imageViewer):
        _translate = QtCore.QCoreApplication.translate
        wid_imageViewer.setWindowTitle(_translate("wid_imageViewer", "ImageView"))
        self.label_imageView.setText(_translate("wid_imageViewer", "image viewer"))
