# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kkt/development/python/gui/socket-server/modules/PyQt6/ui/ui-main.ui'
#
# Created by: PyQt6 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import traceback
from modules.logging_config import get_plugin_logger




# 인자 없이 호출하면 자동으로 현재 모듈 이름(파일 이름)을 사용
logger = get_plugin_logger()

class Ui_MainWindowByDesigner(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1759, 1137)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lcdNumber_Clock = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_Clock.setGeometry(QtCore.QRect(1440, 10, 311, 71))
        self.lcdNumber_Clock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Clock.setStyleSheet("background-color: rgb(0, 0, 0);\n""color: rgb(255, 255, 255);")
        self.lcdNumber_Clock.setDigitCount(8)
        self.lcdNumber_Clock.setObjectName("lcdNumber_Clock")

        self.frame_Connection = QtWidgets.QFrame(self.centralwidget)
        self.frame_Connection.setGeometry(QtCore.QRect(30, 50, 431, 1021))
        self.frame_Connection.setStyleSheet("border:3px solid black;\n""background-color:black;")
        self.frame_Connection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Connection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Connection.setObjectName("frame_Connection")
        self.label_Camera = QtWidgets.QLabel(self.frame_Connection)
        self.label_Camera.setGeometry(QtCore.QRect(20, 110, 391, 351))
        self.label_Camera.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_Camera.setAutoFillBackground(False)
        self.label_Camera.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Camera.setText("")
        self.label_Camera.setPixmap(QtGui.QPixmap("/home/kkt/development/python/gui/socket-server/modules/PyQt6/ui/../../../assets/PyQt6/images/cam-img.png"))
        self.label_Camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Camera.setObjectName("label_Camera")
        self.textBrowser_SpeechToText = QtWidgets.QTextBrowser(self.frame_Connection)
        self.textBrowser_SpeechToText.setGeometry(QtCore.QRect(20, 480, 391, 221))
        self.textBrowser_SpeechToText.setAutoFillBackground(False)
        self.textBrowser_SpeechToText.setStyleSheet("background-color:white")
        self.textBrowser_SpeechToText.setObjectName("textBrowser_SpeechToText")
        self.textEdit_TTS = QtWidgets.QTextEdit(self.frame_Connection)
        self.textEdit_TTS.setGeometry(QtCore.QRect(20, 710, 391, 211))
        self.textEdit_TTS.setStyleSheet("background-color:white;\n""")
        self.textEdit_TTS.setObjectName("textEdit_TTS")
        self.pushButton_TTS = QtWidgets.QPushButton(self.frame_Connection)
        self.pushButton_TTS.setGeometry(QtCore.QRect(130, 930, 161, 31))
        self.pushButton_TTS.setStyleSheet("background-color:white;")
        self.pushButton_TTS.setObjectName("pushButton_TTS")
        self.label_ConnectionTime_Title = QtWidgets.QLabel(self.frame_Connection)
        self.label_ConnectionTime_Title.setGeometry(QtCore.QRect(220, 990, 70, 25))
        self.label_ConnectionTime_Title.setStyleSheet("background-color:white;")
        self.label_ConnectionTime_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ConnectionTime_Title.setObjectName("label_ConnectionTime_Title")
        self.label_connection_time_text = QtWidgets.QLabel(self.frame_Connection)
        self.label_connection_time_text.setGeometry(QtCore.QRect(310, 990, 111, 25))
        self.label_connection_time_text.setStyleSheet("background-color:white;")
        self.label_connection_time_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_connection_time_text.setObjectName("label_connection_time_text")
        self.pushButton_Ctl_Connection = QtWidgets.QPushButton(self.frame_Connection)
        self.pushButton_Ctl_Connection.setGeometry(QtCore.QRect(130, 50, 171, 41))
        self.pushButton_Ctl_Connection.setStyleSheet("background-color:white;")
        self.pushButton_Ctl_Connection.setObjectName("pushButton_Ctl_Connection")

        self.label_Frame_Title = QtWidgets.QLabel(self.frame_Connection)
        self.label_Frame_Title.setGeometry(QtCore.QRect(40, 10, 361, 31))
        self.label_Frame_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Frame_Title.setStyleSheet("background-color:yellow;font-weight:bold\n""")        
        self.label_Frame_Title.setObjectName("label_Frame_Title")

        self.textBrowser_SpeechToText.raise_()
        self.label_Camera.raise_()
        self.textEdit_TTS.raise_()
        self.pushButton_TTS.raise_()
        self.label_ConnectionTime_Title.raise_()
        self.label_connection_time_text.raise_()
        self.pushButton_Ctl_Connection.raise_()
        self.label_Frame_Title.raise_()
        self.frame_Network_Status = QtWidgets.QFrame(self.centralwidget)
        self.frame_Network_Status.setGeometry(QtCore.QRect(1540, 980, 211, 101))
        self.frame_Network_Status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Network_Status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Network_Status.setObjectName("frame_Network_Status")
        self.label_WS_status = QtWidgets.QLabel(self.frame_Network_Status)
        self.label_WS_status.setGeometry(QtCore.QRect(130, 70, 51, 21))
        self.label_WS_status.setStyleSheet("width: 30px;\n"
                                "height: 30px;\n"
                                "border-radius: 10px;\n"
                                "border: 3px solid blue;\n"
                                "background-color:blue;\n"
                                "")
        self.label_WS_status.setText("")
        self.label_WS_status.setObjectName("label_WS_status")
        self.label_Ethernet_Status = QtWidgets.QLabel(self.frame_Network_Status)
        self.label_Ethernet_Status.setGeometry(QtCore.QRect(30, 71, 51, 21))
        self.label_Ethernet_Status.setStyleSheet("width: 30px;\n"
                                                "height: 30px;\n"
                                                "border-radius: 10px;\n"
                                                "border: 3px solid blue;\n"
                                                "background-color:blue;")
        self.label_Ethernet_Status.setText("")
        self.label_Ethernet_Status.setObjectName("label_Ethernet_Status")
        self.label_Web_Socket_Title = QtWidgets.QLabel(self.frame_Network_Status)
        self.label_Web_Socket_Title.setGeometry(QtCore.QRect(110, 40, 91, 20))
        self.label_Web_Socket_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Web_Socket_Title.setObjectName("label_Web_Socket_Title")
        self.label_Ethernet_Title = QtWidgets.QLabel(self.frame_Network_Status)
        self.label_Ethernet_Title.setGeometry(QtCore.QRect(10, 40, 91, 20))
        self.label_Ethernet_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ethernet_Title.setObjectName("label_Ethernet_Title")
        self.label_Network_Status_label = QtWidgets.QLabel(self.frame_Network_Status)
        self.label_Network_Status_label.setGeometry(QtCore.QRect(6, 3, 201, 31))
        self.label_Network_Status_label.setStyleSheet("font-size:24px;background-color:yellow;font-weight:bold")
        self.label_Network_Status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Network_Status_label.setObjectName("label_Network_Status_label")
        self.frame_Connection.raise_()
        self.lcdNumber_Clock.raise_()
        self.frame_Network_Status.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1759, 28))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setStyleSheet("color:blue;\n"
                                        "font-weight:bold;\n"
                                        "")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionEnd = QtWidgets.QAction(MainWindow)
        self.actionEnd.setObjectName("actionEnd")
        self.menuSystem.addAction(self.actionStart)
        self.menuSystem.addAction(self.actionEnd)
        self.menubar.addAction(self.menuSystem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_TTS.setText(_translate("MainWindow", "Voice송신"))
        self.label_ConnectionTime_Title.setText(_translate("MainWindow", "연결시간"))
        self.label_connection_time_text.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_Ctl_Connection.setText(_translate("MainWindow", "연결종료"))
        self.label_Frame_Title.setText(_translate("MainWindow", "미연결"))
        self.label_Web_Socket_Title.setText(_translate("MainWindow", "Web-Socket"))
        self.label_Ethernet_Title.setText(_translate("MainWindow", "Ethernet"))
        self.label_Network_Status_label.setText(_translate("MainWindow", "Network Status"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionEnd.setText(_translate("MainWindow", "End"))
